/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleFleetRouteImport } from './routes/console/fleet'
import { Route as ConsoleStorageRouteImport } from './routes/console/storage'
import { Route as ConsoleValidateRouteImport } from './routes/console/validate'
import { Route as DesktopWorkspaceIdRouteImport } from './routes/desktop.$workspaceId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleFleetRoute = ConsoleFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleStorageRoute = ConsoleStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleValidateRoute = ConsoleValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => ConsoleRoute,
} as any)
const DesktopWorkspaceIdRoute = DesktopWorkspaceIdRouteImport.update({
  id: '/desktop/$workspaceId',
  path: '/desktop/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/console/fleet': typeof ConsoleFleetRoute
  '/console/storage': typeof ConsoleStorageRoute
  '/console/validate': typeof ConsoleValidateRoute
  '/desktop/$workspaceId': typeof DesktopWorkspaceIdRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/console/fleet': typeof ConsoleFleetRoute
  '/console/storage': typeof ConsoleStorageRoute
  '/console/validate': typeof ConsoleValidateRoute
  '/desktop/$workspaceId': typeof DesktopWorkspaceIdRoute
  '/console': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/console/fleet': typeof ConsoleFleetRoute
  '/console/storage': typeof ConsoleStorageRoute
  '/console/validate': typeof ConsoleValidateRoute
  '/desktop/$workspaceId': typeof DesktopWorkspaceIdRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/login'
    | '/console/fleet'
    | '/console/storage'
    | '/console/validate'
    | '/desktop/$workspaceId'
    | '/console/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/console/fleet'
    | '/console/storage'
    | '/console/validate'
    | '/desktop/$workspaceId'
    | '/console'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/login'
    | '/console/fleet'
    | '/console/storage'
    | '/console/validate'
    | '/desktop/$workspaceId'
    | '/console/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
  DesktopWorkspaceIdRoute: typeof DesktopWorkspaceIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/fleet': {
      id: '/console/fleet'
      path: '/fleet'
      fullPath: '/console/fleet'
      preLoaderRoute: typeof ConsoleFleetRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/storage': {
      id: '/console/storage'
      path: '/storage'
      fullPath: '/console/storage'
      preLoaderRoute: typeof ConsoleStorageRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/validate': {
      id: '/console/validate'
      path: '/validate'
      fullPath: '/console/validate'
      preLoaderRoute: typeof ConsoleValidateRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/desktop/$workspaceId': {
      id: '/desktop/$workspaceId'
      path: '/desktop/$workspaceId'
      fullPath: '/desktop/$workspaceId'
      preLoaderRoute: typeof DesktopWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleFleetRoute: typeof ConsoleFleetRoute
  ConsoleStorageRoute: typeof ConsoleStorageRoute
  ConsoleValidateRoute: typeof ConsoleValidateRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleFleetRoute: ConsoleFleetRoute,
  ConsoleStorageRoute: ConsoleStorageRoute,
  ConsoleValidateRoute: ConsoleValidateRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
  DesktopWorkspaceIdRoute: DesktopWorkspaceIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
